<?php
$oauth_clients = array(
    array(
        "id" => 1,
        "user_id" => null,
        "name" => "Laravel Personal Access Client",
        "secret" => "jAZRgu9vZsBBJt3ZCokppflchSRxSeDLMJSkMQfI",
        "provider" => null,
        "redirect" => "http://localhost",
        "personal_access_client" => 1,
        "password_client" => 0,
        "revoked" => 0,
        "created_at" => "2024-04-17 01:47:30",
        "updated_at" => "2024-04-17 01:47:30",
    ),
);
$oauth_personal_access_clients = array(
    array(
        "id" => 1,
        "client_id" => 1,
        "created_at" => "2024-04-17 01:47:30",
        "updated_at" => "2024-04-17 01:47:30",
    ),
);

$months = array(
    array(
        "id" => 1,
        "name" => "January",
        "short_name" => "JAN",
        "number" => 1,
        "no_of_days" => 31,
        "is_february" => 0,
        "created_at" => "2024-06-06 08:20:03",
        "updated_at" => "2024-06-06 08:20:04",
    ),
    array(
        "id" => 2,
        "name" => "February",
        "short_name" => "FEB",
        "number" => 2,
        "no_of_days" => 28,
        "is_february" => 1,
        "created_at" => "2024-06-06 08:20:03",
        "updated_at" => "2024-06-06 08:20:04",
    ),
    array(
        "id" => 3,
        "name" => "March",
        "short_name" => "MAR",
        "number" => 3,
        "no_of_days" => 31,
        "is_february" => 0,
        "created_at" => "2024-06-06 08:20:03",
        "updated_at" => "2024-06-06 08:20:04",
    ),
    array(
        "id" => 4,
        "name" => "April",
        "short_name" => "APR",
        "number" => 4,
        "no_of_days" => 30,
        "is_february" => 0,
        "created_at" => "2024-06-06 08:20:03",
        "updated_at" => "2024-06-06 08:20:04",
    ),
    array(
        "id" => 5,
        "name" => "May",
        "short_name" => "MAY",
        "number" => 5,
        "no_of_days" => 31,
        "is_february" => 0,
        "created_at" => null,
        "updated_at" => null,
    ),
    array(
        "id" => 6,
        "name" => "June",
        "short_name" => "JUN",
        "number" => 6,
        "no_of_days" => 30,
        "is_february" => 0,
        "created_at" => null,
        "updated_at" => null,
    ),
    array(
        "id" => 7,
        "name" => "July",
        "short_name" => "JUL",
        "number" => 7,
        "no_of_days" => 31,
        "is_february" => 0,
        "created_at" => null,
        "updated_at" => null,
    ),
    array(
        "id" => 8,
        "name" => "August",
        "short_name" => "AUG",
        "number" => 8,
        "no_of_days" => 31,
        "is_february" => 0,
        "created_at" => null,
        "updated_at" => null,
    ),
    array(
        "id" => 9,
        "name" => "September",
        "short_name" => "SEP",
        "number" => 9,
        "no_of_days" => 30,
        "is_february" => 0,
        "created_at" => null,
        "updated_at" => null,
    ),
    array(
        "id" => 10,
        "name" => "October",
        "short_name" => "OCT",
        "number" => 10,
        "no_of_days" => 31,
        "is_february" => 0,
        "created_at" => null,
        "updated_at" => null,
    ),
    array(
        "id" => 11,
        "name" => "November",
        "short_name" => "NOV",
        "number" => 11,
        "no_of_days" => 30,
        "is_february" => 0,
        "created_at" => null,
        "updated_at" => null,
    ),
    array(
        "id" => 12,
        "name" => "December",
        "short_name" => "DEC",
        "number" => 12,
        "no_of_days" => 31,
        "is_february" => 0,
        "created_at" => null,
        "updated_at" => null,
    ),
);
$sections = array(
    array(
        "id" => 1,
        "name" => "A",
        "code" => "A",
        "created_at" => "2024-04-18 08:59:45",
        "updated_at" => "2024-04-18 08:59:45",
    ),
    array(
        "id" => 2,
        "name" => "B",
        "code" => "B",
        "created_at" => "2024-04-18 08:59:53",
        "updated_at" => "2024-04-18 08:59:53",
    ),
    array(
        "id" => 3,
        "name" => "C",
        "code" => "C",
        "created_at" => "2024-04-18 08:59:58",
        "updated_at" => "2024-04-18 08:59:58",
    ),
    array(
        "id" => 4,
        "name" => "D",
        "code" => "D",
        "created_at" => "2024-04-18 09:00:03",
        "updated_at" => "2024-04-18 09:00:03",
    ),
);
$states = array(
    array(
        "id" => 1,
        "name" => "WEST BENGAL",
        "state_code" => "WB",
        "country_id" => 1,
        "created_at" => "2024-04-16 06:52:53",
        "updated_at" => "2024-04-16 06:52:53",
    ),
);
$subject_groups = array(
    array(
        "id" => 1,
        "name" => "Bengali",
        "code" => "BN",
        "description" => null,
        "logo_image_id" => null,
        "created_at" => "2024-04-17 07:18:07",
        "updated_at" => "2024-04-17 07:18:07",
    ),
    array(
        "id" => 2,
        "name" => "English",
        "code" => "ENG",
        "description" => null,
        "logo_image_id" => null,
        "created_at" => "2024-04-17 07:18:22",
        "updated_at" => "2024-04-17 07:18:22",
    ),
    array(
        "id" => 3,
        "name" => "Mathematics",
        "code" => "Math",
        "description" => null,
        "logo_image_id" => null,
        "created_at" => "2024-04-17 07:18:59",
        "updated_at" => "2024-04-17 07:18:59",
    ),
    array(
        "id" => 4,
        "name" => "Science",
        "code" => "SC",
        "description" => null,
        "logo_image_id" => null,
        "created_at" => "2024-04-17 07:19:10",
        "updated_at" => "2024-04-17 07:19:10",
    ),
    array(
        "id" => 5,
        "name" => "History",
        "code" => "HIS",
        "description" => null,
        "logo_image_id" => null,
        "created_at" => "2024-04-17 07:19:46",
        "updated_at" => "2024-04-17 07:19:46",
    ),
    array(
        "id" => 6,
        "name" => "Geography",
        "code" => "GEO",
        "description" => null,
        "logo_image_id" => null,
        "created_at" => "2024-04-17 07:20:02",
        "updated_at" => "2024-04-17 07:20:02",
    ),
    array(
        "id" => 7,
        "name" => "Work Education",
        "code" => "WE",
        "description" => null,
        "logo_image_id" => null,
        "created_at" => "2024-04-17 07:20:17",
        "updated_at" => "2024-04-17 07:20:17",
    ),
    array(
        "id" => 8,
        "name" => "Physical Education",
        "code" => "PE",
        "description" => null,
        "logo_image_id" => null,
        "created_at" => "2024-04-17 07:20:29",
        "updated_at" => "2024-04-17 07:20:29",
    ),
    array(
        "id" => 9,
        "name" => "Computer",
        "code" => "COMP",
        "description" => null,
        "logo_image_id" => null,
        "created_at" => "2024-04-17 07:21:07",
        "updated_at" => "2024-04-17 07:21:07",
    ),
);
$subjects = array(
    array(
        "id" => 1,
        "name" => "Bengali for Nursery1",
        "code" => "BENG",
        "subject_type" => "objective",
        "subject_group_id" => 1,
        "academic_standard_id" => 1,
        "description" => null,
        "logo_image_id" => null,
        "is_active" => 0,
        "created_at" => "2024-04-17 07:28:40",
        "updated_at" => "2024-04-20 06:41:58",
    ),
    array(
        "id" => 2,
        "name" => "English for Nursery1",
        "code" => "English",
        "subject_type" => "subjective",
        "subject_group_id" => 2,
        "academic_standard_id" => 1,
        "description" => null,
        "logo_image_id" => null,
        "is_active" => 0,
        "created_at" => "2024-04-17 08:11:48",
        "updated_at" => "2024-04-17 08:11:48",
    ),
);

$schools = array(
    array(
        "id" => 1,
        "name" => "Navajyoti Vidyapith",
        "code" => "NV",
        "education_board_id" => 1,
        "address_id" => null,
        "contact_no" => "3333337777",
        "email" => "nvifno@gmail.com",
        "website" => "www.tb.org",
        "establishment_date" => "2024-05-11",
        "school_type_id" => 1,
        "logo_image_id" => null,
        "created_at" => "2024-04-16 06:52:53",
        "updated_at" => "2024-05-11 08:15:33",
    ),
);
$school_types = array(
    array(
        "id" => 1,
        "name" => "HINDI MEDIUM",
    ),
);
$academic_sessions = array(
    array(
        "id" => 1,
        "campus_id" => 1,
        "session" => "2023",
        "start_date" => "2023-01-01",
        "end_date" => "2023-12-31",
        "previous_academic_session_id" => null,
        "next_academic_session_id" => 2,
        "is_current" => 0,
        "created_at" => "2024-04-16 06:52:53",
        "updated_at" => "2024-06-05 00:28:10",
        "current_fee_no" => 1,
        "current_expense_no" => 13,
    ),
    array(
        "id" => 2,
        "campus_id" => 1,
        "session" => "2024",
        "start_date" => "2024-01-01",
        "end_date" => "2024-12-31",
        "previous_academic_session_id" => 1,
        "next_academic_session_id" => 3,
        "is_current" => 1,
        "created_at" => "2024-04-16 06:52:53",
        "updated_at" => "2024-06-05 00:22:25",
        "current_fee_no" => 1,
        "current_expense_no" => 2,
    ),
    array(
        "id" => 3,
        "campus_id" => 1,
        "session" => "2025",
        "start_date" => "2025-01-01",
        "end_date" => "2025-12-31",
        "previous_academic_session_id" => 2,
        "next_academic_session_id" => null,
        "is_current" => 0,
        "created_at" => "2024-04-16 06:52:53",
        "updated_at" => "2024-05-30 00:24:28",
        "current_fee_no" => 1,
        "current_expense_no" => 1,
    ),
);
$academic_standards = array(
    array(
        "id" => 1,
        "name" => "Nursery I",
        "code" => "N-I",
        "description" => "Nursery I",
        "created_at" => "2024-04-17 07:14:12",
        "updated_at" => "2024-05-28 21:27:33",
    ),
    array(
        "id" => 2,
        "name" => "Nursery II",
        "code" => "N-II",
        "description" => "Nursery II",
        "created_at" => "2024-04-17 07:14:24",
        "updated_at" => "2024-05-28 21:27:48",
    ),
    array(
        "id" => 3,
        "name" => "Kinder Garten I",
        "code" => "KG1",
        "description" => null,
        "created_at" => "2024-04-17 07:14:48",
        "updated_at" => "2024-04-17 07:14:48",
    ),
    array(
        "id" => 4,
        "name" => "Kinder Garten II",
        "code" => "KG2",
        "description" => null,
        "created_at" => "2024-04-17 07:15:00",
        "updated_at" => "2024-04-17 07:15:00",
    ),
    array(
        "id" => 5,
        "name" => "Standard 1",
        "code" => "S1",
        "description" => null,
        "created_at" => "2024-04-17 07:15:16",
        "updated_at" => "2024-04-17 07:15:16",
    ),
    array(
        "id" => 6,
        "name" => "Standard 2",
        "code" => "S2",
        "description" => null,
        "created_at" => "2024-04-17 07:15:26",
        "updated_at" => "2024-04-17 07:15:26",
    ),
    array(
        "id" => 7,
        "name" => "Standard 3",
        "code" => "S3",
        "description" => null,
        "created_at" => "2024-04-17 07:15:42",
        "updated_at" => "2024-04-17 07:15:42",
    ),
    array(
        "id" => 8,
        "name" => "Standard 4",
        "code" => "S4",
        "description" => null,
        "created_at" => "2024-04-17 07:15:54",
        "updated_at" => "2024-04-17 07:15:54",
    ),
    array(
        "id" => 9,
        "name" => "Standard 5",
        "code" => "S5",
        "description" => null,
        "created_at" => "2024-04-17 07:16:04",
        "updated_at" => "2024-04-17 07:16:04",
    ),
    array(
        "id" => 10,
        "name" => "Standard 6",
        "code" => "S6",
        "description" => null,
        "created_at" => "2024-04-17 07:16:17",
        "updated_at" => "2024-04-17 07:16:17",
    ),
    array(
        "id" => 11,
        "name" => "Standard 7",
        "code" => "S7",
        "description" => null,
        "created_at" => "2024-04-17 07:16:27",
        "updated_at" => "2024-04-17 07:16:27",
    ),
    array(
        "id" => 12,
        "name" => "Standard 8",
        "code" => "S8",
        "description" => null,
        "created_at" => "2024-04-17 07:16:36",
        "updated_at" => "2024-04-17 07:16:36",
    ),
    array(
        "id" => 13,
        "name" => "Standard 9",
        "code" => "S9",
        "description" => null,
        "created_at" => "2024-04-17 07:16:48",
        "updated_at" => "2024-04-17 07:16:48",
    ),
    array(
        "id" => 14,
        "name" => "Standard 10",
        "code" => "S10",
        "description" => null,
        "created_at" => "2024-04-17 07:16:59",
        "updated_at" => "2024-04-17 07:16:59",
    ),
);

$campuses = array(
    array(
        "id" => 1,
        "school_id" => 1,
        "education_board_id" => 1,
        "name" => "Primary Section",
        "code" => "PC",
        "address_id" => null,
        "contact_no" => "3333337777",
        "email" => "ps@gmail.com",
        "establishment_date" => "2024-05-11",
        "opening_time" => null,
        "closing_time" => null,
        "logo_image_id" => null,
        "created_at" => "2024-04-16 06:52:53",
        "updated_at" => "2024-05-11 08:16:19",
    ),
    array(
        "id" => 2,
        "school_id" => 1,
        "education_board_id" => 1,
        "name" => "Secondary Section",
        "code" => "SC",
        "address_id" => null,
        "contact_no" => null,
        "email" => null,
        "establishment_date" => null,
        "opening_time" => null,
        "closing_time" => null,
        "logo_image_id" => null,
        "created_at" => "2024-04-16 06:52:53",
        "updated_at" => "2024-04-16 06:52:53",
    ),
    array(
        "id" => 3,
        "school_id" => 1,
        "education_board_id" => 1,
        "name" => "Secondary Section- board",
        "code" => "SSB",
        "address_id" => null,
        "contact_no" => null,
        "email" => null,
        "establishment_date" => "2024-04-20",
        "opening_time" => null,
        "closing_time" => null,
        "logo_image_id" => null,
        "created_at" => "2024-04-20 08:49:43",
        "updated_at" => "2024-04-20 08:49:43",
    ),
    array(
        "id" => 4,
        "school_id" => 1,
        "education_board_id" => 1,
        "name" => "Other Campus",
        "code" => "OC",
        "address_id" => null,
        "contact_no" => null,
        "email" => null,
        "establishment_date" => "2024-04-20",
        "opening_time" => null,
        "closing_time" => null,
        "logo_image_id" => null,
        "created_at" => "2024-04-20 08:53:09",
        "updated_at" => "2024-04-20 08:53:09",
    ),
);
$education_boards = array(
    array(
        "id" => 1,
        "name" => "West Bengal Board Of Secondary Education",
        "code" => "WBBSE",
        "address_id" => null,
        "description" => null,
        "contact_no" => null,
        "email" => null,
        "website" => null,
        "establishment_date" => null,
        "logo_image_id" => null,
        "created_at" => "2024-04-16 06:52:53",
        "updated_at" => "2024-04-16 06:52:53",
    ),
);
$fee_heads = array(
    array(
        "id" => 1,
        "name" => "ADMISSION FEE",
        "created_at" => "2024-04-20 06:53:49",
        "updated_at" => "2024-04-22 01:11:30",
    ),
    array(
        "id" => 2,
        "name" => "SESSION FEE",
        "created_at" => "2024-04-20 06:54:14",
        "updated_at" => "2024-04-20 07:08:29",
    ),
    array(
        "id" => 3,
        "name" => "MONTHLY FEE",
        "created_at" => "2024-04-20 06:54:22",
        "updated_at" => "2024-04-20 07:08:24",
    ),
    array(
        "id" => 4,
        "name" => "Examination Fee",
        "created_at" => "2024-04-20 06:54:55",
        "updated_at" => "2024-04-20 07:08:19",
    ),
    array(
        "id" => 5,
        "name" => "Development Fee",
        "created_at" => "2024-04-20 07:08:01",
        "updated_at" => "2024-04-20 07:08:01",
    ),
    array(
        "id" => 6,
        "name" => "Game Fee",
        "created_at" => "2024-04-20 07:08:14",
        "updated_at" => "2024-04-20 07:08:14",
    ),
    array(
        "id" => 7,
        "name" => "Library Fee",
        "created_at" => "2024-04-20 07:08:47",
        "updated_at" => "2024-04-20 07:08:47",
    ),
    array(
        "id" => 8,
        "name" => "S. Puja",
        "created_at" => "2024-04-20 07:09:03",
        "updated_at" => "2024-04-20 07:09:03",
    ),
    array(
        "id" => 9,
        "name" => "Transport Fee",
        "created_at" => "2024-04-20 07:09:16",
        "updated_at" => "2024-04-20 07:09:16",
    ),
);

$transport_types = array(
    array(
        "id" => 1,
        "name" => "School Bus",
        "created_at" => null,
        "updated_at" => null,
    ),
    array(
        "id" => 2,
        "name" => "Pool Car",
        "created_at" => null,
        "updated_at" => null,
    ),
);
$journey_types = array(

    array(
        "id" => 1,
        "name" => "Pickup and Drop",
        "created_at" => null,
        "updated_at" => null,
    ),
    array(
        "id" => 2,
        "name" => "Pickup Only",
        "created_at" => null,
        "updated_at" => null,
    ),
    array(
        "id" => 3,
        "name" => "Drop Only",
        "created_at" => null,
        "updated_at" => null,
    ),
);

$users = array(
    array(
        "id" => 1,
        "name" => "Super-Admin User",
        "username" => "SUPERADMIN",
        "code" => null,
        "user_type" => "super_admin",
        "email" => "superadmin@example.com",
        "email_verified_at" => "2024-04-16 06:52:53",
        "contact_no" => "2878412361",
        "contact_no_verified_at" => null,
        "password" => "$2y$12$jP7vFErxRR8qlOp2dzZRleqWlnyJxpninSAMCvHl.8mNdp5PQTg7e",
        "status" => "active",
        "emergency_contact_name" => "Lolita Zemlak V",
        "emergency_contact_no" => "1293899071",
        "birth_mark" => "voluptatem",
        "medical_conditions" => "dicta",
        "allergies" => "repellat",
        "language" => "ru",
        "nationality" => "indian",
        "religion" => null,
        "caste" => null,
        "guardian_type" => "other",
        "address_id" => 1,
        "department_id" => null,
        "designation_id" => null,
        "campus_id" => null,
        "academic_session_id" => null,
        "academic_class_id" => null,
        "gender" => "other",
        "doj" => "2011-12-19",
        "dob" => "1974-10-28",
        "dob_log" => null,
        "aadhaar_no" => "a",
        "pan_no" => "et",
        "passport_no" => "sit",
        "profile_document_id" => null,
        "bank_name" => "sint",
        "account_holder_name" => "deleniti",
        "bank_account_no" => null,
        "bank_ifsc" => "dolorem",
        "bank_branch" => "quia",
        "admission_no" => null,
        "admission_date" => null,
        "remember_token" => "dL4XDX9sQo",
        "created_at" => "2024-04-16 06:52:53",
        "updated_at" => "2024-04-16 06:52:53",
    ),
    array(
        "id" => 2,
        "name" => "Admin User",
        "username" => "ADMIN00000",
        "code" => null,
        "user_type" => "admin",
        "email" => "admin@example.com",
        "email_verified_at" => "2024-04-16 06:52:53",
        "contact_no" => "2670759277",
        "contact_no_verified_at" => null,
        "password" => "$2y$12$jP7vFErxRR8qlOp2dzZRleqWlnyJxpninSAMCvHl.8mNdp5PQTg7e",
        "status" => "active",
        "emergency_contact_name" => "Mckayla Kerluke III",
        "emergency_contact_no" => "4164080789",
        "birth_mark" => "aut",
        "medical_conditions" => "iure",
        "allergies" => "numquam",
        "language" => "bn",
        "nationality" => "indian",
        "religion" => null,
        "caste" => null,
        "guardian_type" => "father",
        "address_id" => 1,
        "department_id" => null,
        "designation_id" => null,
        "campus_id" => null,
        "academic_session_id" => null,
        "academic_class_id" => null,
        "gender" => "female",
        "doj" => "1990-11-24",
        "dob" => "2018-03-14",
        "dob_log" => null,
        "aadhaar_no" => "sit",
        "pan_no" => "quia",
        "passport_no" => "quam",
        "profile_document_id" => null,
        "bank_name" => "qui",
        "account_holder_name" => "consequatur",
        "bank_account_no" => null,
        "bank_ifsc" => "inventore",
        "bank_branch" => "quasi",
        "admission_no" => null,
        "admission_date" => null,
        "remember_token" => "zqaozvI8Qu",
        "created_at" => "2024-04-16 06:52:53",
        "updated_at" => "2024-04-16 06:52:53",
    ),
);
